# Generated by Django 3.1.7 on 2021-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgroUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[(1, 'Jismoniy_Shaxs'), (2, 'Yuridik_Shaxs')], max_length=50, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
